# Generated by Django 3.2.6 on 2021-12-10 18:24

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=50, null=True)),
                ('First_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Last_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Password1', models.CharField(blank=True, max_length=100, null=True)),
                ('Password2', models.CharField(blank=True, max_length=100, null=True)),
                ('DOB', models.DateTimeField(blank=True, null=True)),
                ('Company', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('Address2', models.CharField(blank=True, max_length=100, null=True)),
                ('City', models.CharField(blank=True, max_length=100, null=True)),
                ('State', models.CharField(blank=True, max_length=200, null=True)),
                ('Zip_Code', models.CharField(blank=True, max_length=20, null=True)),
                ('Country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('Additional_Info', models.TextField(blank=True, null=True)),
                ('Home_Phone', models.CharField(blank=True, max_length=100, null=True)),
                ('Mobile_Phone', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
