# Generated by Django 3.2.6 on 2021-12-19 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211211_0030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Register',
        ),
    ]
