# Generated by Django 3.2.6 on 2021-11-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=200, null=True)),
                ('prod_price', models.FloatField(null=True)),
                ('prod_img1', models.ImageField(null=True, upload_to='')),
                ('prod_img2', models.ImageField(null=True, upload_to='')),
                ('prod_img3', models.ImageField(null=True, upload_to='')),
                ('prod_img4', models.ImageField(null=True, upload_to='')),
                ('prod_img5', models.ImageField(null=True, upload_to='')),
                ('prod_img6', models.ImageField(null=True, upload_to='')),
                ('prod_img7', models.ImageField(null=True, upload_to='')),
                ('prod_desc', models.TextField(null=True)),
                ('prod_cat', models.CharField(choices=[('Clothes', 'Clothes'), ('Food & Beverages', 'Food & Beverages'), ('Health & Beauty', 'Health & Beauty'), ('Sports & Leisure', 'Sports & Leisure'), ('Books & Entertainment', 'Books & Entertainment')], max_length=200, null=True)),
                ('prod_color', models.CharField(choices=[('Black', 'Black'), ('Red', 'Red'), ('Blue', 'Blue'), ('Brown', 'Brown')], max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
