# Generated by Django 3.2.6 on 2021-12-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_cat',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Clothes', 'Clothes'), ('Food & Beverages', 'Food & Beverages'), ('Health & Beauty', 'Health & Beauty'), ('Sports & Leisure', 'Sports & Leisure'), ('Books & Entertainment', 'Books & Entertainment')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_img1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_img2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_img3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_img4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_img5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_img6',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_img7',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
