# Generated by Django 3.2.6 on 2021-12-03 17:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211203_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prod_desc',
            new_name='prod_summary',
        ),
        migrations.AddField(
            model_name='product',
            name='prod_information',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
