# Generated by Django 3.2.6 on 2021-12-06 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211203_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prod_color',
        ),
    ]
