# Generated by Django 3.2.6 on 2021-12-06 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_product_prod_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_cat',
            field=models.CharField(blank=True, choices=[('Electronics', 'Electronics'), ('Clothes', 'Clothes'), ('Food & Beverages', 'Food & Beverages'), ('Health & Beauty', 'Health & Beauty'), ('Sports & Leisure', 'Sports & Leisure'), ('Books & Entertainment', 'Books & Entertainment')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnty', models.PositiveSmallIntegerField(default=1)),
                ('name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
    ]
