# Generated by Django 3.2.6 on 2021-12-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
