# Generated by Django 3.2.6 on 2021-12-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_cart_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='Total',
            new_name='tax',
        ),
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
