# Generated by Django 3.2.6 on 2021-12-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20211211_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='unit_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
