# Generated by Django 3.2.6 on 2021-12-17 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_product_prod_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_cat',
            field=models.CharField(blank=True, choices=[('Electronics', 'Electronics'), ('Clothes', 'Clothes'), ('Food & Beverages', 'Food & Beverages'), ('Health & Beauty', 'Health & Beauty'), ('Sports & Leisure', 'Sports & Leisure'), ('Books & Entertainment', 'Books & Entertainment')], max_length=200, null=True),
        ),
    ]
