# Generated by Django 3.2.6 on 2021-12-17 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20211217_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cat',
        ),
    ]
