# Generated by Django 3.2.6 on 2021-12-17 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_rename_category_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
