# Generated by Django 3.2.6 on 2021-12-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='twenty_percent_discount',
            field=models.BooleanField(blank=True, default='False', null=True),
        ),
    ]
