# Generated by Django 3.2.6 on 2021-12-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_product_twenty_percent_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='twenty_percent_discount',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
