# Generated by Django 3.2.6 on 2021-12-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20211221_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_discount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
